### DISCUSSION TITLE
Change slide animation

### DISCUSSION THREAD

**Discussion by mateusz-wyka** [ismail9k/vue3-carousel#258] [Q&A] [answered]
Hi, I would like to use `cubic-bezier`. Is it possible to change the slide animation?

**Comment by ismail9k** [comment, marked as answer]
You can change it using CSS

```css
.carousel__track {
    transition-timing-function: cubic-bezier(0.18, 0.89, 0.32, 1.28) !important;
}
```
