### DISCUSSION TITLE
Example style in Tailwind

### DISCUSSION THREAD

**Discussion by oneWaveAdrian** [ismail9k/vue3-carousel#74] [Show and tell]
If anyone needs it, I "translated" the css-file from the example into [Tailwind.css
](https://tailwindcss.com/)
```css
<style>
.carousel__icon {
  width: 1.2em;
  height: 1.2em;
  fill: currentColor;
}
.carousel {
  @apply relative text-center box-border;
}

.carousel * {
  @apply box-border;
}

.carousel__track {
  @apply flex m-0 p-0 relative;
}

.carousel__viewport {
  @apply overflow-hidden;
}
.carousel__pagination {
  @apply flex justify-center list-none;
}
.carousel__pagination-button {
  @apply cursor-pointer bg-blue-400 border-0 rounded-full h-4 w-4 mx-1 my-4;
}

.carousel__pagination-button--active {
  @apply bg-blue-800;
}

.carousel__slide {
  scroll-snap-stop: auto;
  @apply flex justify-center items-center relative m-0 flex-shrink-0;
}
.carousel__prev,
.carousel__next {
  @apply text-white bg-blue-400 cursor-pointer text-center flex border-0 absolute justify-center items-center p-0 w-20 h-20 rounded-full text-6xl;
}

.carousel__prev {
  @apply transform -translate-x-1/2 -translate-y-1/2 left-0 top-1/2;
}

.carousel__next {
  @apply transform translate-x-1/2 -translate-y-1/2 right-0 top-1/2;
}
</style>
```
