### ISSUE TITLE
Slide animation not working

### ISSUE THREAD

**Issue by elchinzadeh** [ismail9k/vue3-carousel#11]
**Description**
Slide animation not working. When I click any of navigation buttons, the `transform` style of the element with class name `carousel _track` does not change. But it works normally in examples. I think it is bug. Or am I wrong somewhere?

**Steps to reproduce the behavior:**
1. Click navigation button
2. See the bug

**My code**
```vue
<Carousel :wrap-around="true" :settings="settings">
    <Slide v-for="slide in 10" :key="slide">
        <div class="carousel__item">
            {{ slide }}
        </div>
    </Slide>

    <template #addons>
        <Navigation />
        <!-- <Pagination /> -->
    </template>
</Carousel>
```

```javascript
<script>
import { Carousel, Slide, Navigation } from 'vue3-carousel';
import 'vue3-carousel/dist/carousel.css';

export default {
    name: 'ProductDrawer',
    components: {
        Carousel,
        Slide,
        Navigation
    },
    props: {
        open: {
            type: Boolean
        },
        productId: {
            type: Number
        }
    },
    data () {
        return {
            settings: {
                itemsToShow: 1,
                snapAlign: 'center'
            }
        };
    }
}
</script>
```

```css
.carousel__item {
    min-height: 200px;
    width: 100%;
    background-color: #642afb;
    color: white;
    font-size: 20px;
    border-radius: 8px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.carousel__slide {
    padding: 10px;
}

.carousel__prev,
.carousel__next {
    box-sizing: content-box;
    border: 5px solid white;
}
```
