### ISSUE TITLE
Add disabled class

### ISSUE THREAD

**Issue by azizullahsaeidi** [ismail9k/vue3-carousel#132]
**Is your feature request related to a problem? Please describe.**

Let me explain my problem with an example:

1. I have 10 images for now both arrow buttons (next & prev) are active. in this case user doesn't know on which button should click (next or prev) because both of them are active. in this case prev button should be disable.

2. if I put  **items-to-show="1"** and I have just one image so both Next and Prev buttons should be disabled but now they are active.

**Describe the solution you'd like**

 you can handle this issue via image lists. or you can add a new class **disabled** on that time your user can handle that. thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by thalida** [comment]
The code here should work for you @azizullahsaeidi: https://github.com/ismail9k/vue3-carousel/issues/45#issuecomment-836309031

CSS
```css
  .carousel__prev.is-first-slide {
    display: none;
  }
  .carousel__next.is-last-slide {
    display: none;
  }
```
