### ISSUE TITLE
Carousel works only after the page is resized 

### ISSUE THREAD

**Issue by joshuadsouza08** [ismail9k/vue3-carousel#134]
The carousel displays the images when mounted but does not go to the next image unless the page is resized and this happens only if there is a 'd-flex' bootstrap property in the parent Div element, without the 'd-flex' the carousel works fine. is there any reason for this?

**Comment by thalida** [comment]
I ran into a similar issue as joshua today when creating an image carousel, on load the carousel wasn't scrolling fully to the next page until I resized the window (see bug gif below). In my case `updateSlideWidth` is called before the images load, so it gets the default slide width of ~200px. The easiest solution for me was to update my css to have a fixed width. 

I'm curious what your template and css looks like @joshuadsouza08? 
(I commented on this issue instead of creating a new one since it's a similar outcome "the carousel only works after the page is resized", but might be caused for different reasons, and may require a new issue depending on how ismail9k wants to do tracking. The solution for mine could be adding an image carousel example to the documentation, instead of a logic change.)  

**Template / CSS To Reproduce:**
template:
```html
<div class="gallery">
    <carousel>
      <slide v-for="photo in photos as any[]" :key="photo.id">
        <div class="carousel__item">
          <img :src="photo.image_url" alt="" />
        </div>
      </slide>
      <template #addons>
        <navigation />
      </template>
    </carousel>
</div>
```

original css:
```css
.carousel__item {
  min-height: 200px;
  width: 100%;
  background-color: var(--vc-clr-primary);
  color: var(--vc-clr-white);
  border-radius: 8px;
  display: flex;
  justify-content: center;
  align-items: center;

  img {
    height: 100%;
  }
}
```
bug gif:
![before](https://user-images.githubusercontent.com/3401715/145106478-3ef30704-d07f-4ecf-8ff4-a02ee59861df.gif)


**Solution**
(same template)
Updated css:
```css
.carousel__item {
  height: 500px;
  width: 500px; // instead of 100%
  background-color: var(--vc-clr-primary);
  color: var(--vc-clr-white);
  border-radius: 8px;
  display: flex;
  justify-content: center;
  align-items: center;

  img {
    width: 100%; // constrain image width
  }
}
```
fixed gif:
![after](https://user-images.githubusercontent.com/3401715/145106498-c6b5001e-359d-4885-b4d5-b16b8d8aaaf6.gif)
