### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by UnKn0wNnnn** [ismail9k/vue3-carousel#178]
How to adjust the pagination dot indicator width when it's on active slide?

**Comment by AustinThornley** [comment]
You want to style this class in your CSS

`.carousel__pagination-button--active`

**Comment by UnKn0wNnnn** [comment]
![image](https://user-images.githubusercontent.com/87200522/165766697-5ee9bdff-66bb-45c9-b24e-b0849364b8b2.png) This is my style, I already did the changing of color when the slide is on active but I don't how to make the width of the dot indicator change too.

**Comment by ismail9k** [comment]
You can apply this snippet 

```css
.carousel__pagination-button.carousel__pagination-button--active {
    width: 100px;
}
```
