### ISSUE TITLE
Slider Fade Animation

### ISSUE THREAD

**Issue by jigarf504** [ismail9k/vue3-carousel#297]
**do you add fade in-out animation effect in the future like this one?** 

[fade in animation](https://gs-shop.github.io/vue-slick-carousel/#/example/fade)

looking forward to hearing from you.

Thanks

**Comment by ismail9k** [comment]
Sure I can support it in the future, but as you can see there're a lots of feature requests, so supporting this as well could take sometime.

**Comment by NawinKumarSharma** [comment]
can you explain the feature properly? I want to work on it

**Comment by jigarf504** [comment]
I want to fade in/out transition effect same like vue slick carousel. you can find the example by this link. https://gs-shop.github.io/vue-slick-carousel/#/example/fade

**Comment by surgiie** [comment]
Looking for this support as well. Is it possible to overwrite the styles ?

**Comment by Tofandel** [comment]
```css
.carousel__slide {
    opacity: 0;
    transition: opacity .3s step-end;
}
.carousel__slide--active {
    opacity: 1;
    transition-timing-function: ease;
}
.carousel__track {
    transition: none !important;
}
```
